### ISSUE TITLE
Swift 2

### ISSUE THREAD

**Issue by grosch** [objcio/functional-programming-in-swift#107]
When will the book be updated for Swift 2?  The entire generator/sequence chapter is now kind of out of date as they've done away with what you've shown.

**Comment by floriankugler** [comment]
@grosch We're basically just waiting to copy-editing done on the update.

Could you be more specific what you mean by "as they've done away with what you've shown"?

**Comment by grosch** [comment]
GeneratorOf<Int> will give a compiler error saying 'GeneratorOf' has been renamed to 'AnyGenerator'

**Comment by floriankugler** [comment]
@grosch Ah ok – yes, the API has changed, but the concepts are still there. The updated book will of course account for those changes.

**Comment by yas375** [comment]
Thanks for updating the book! And for making a beta of the updated book available for those who bought the book. Any chance you can also share updated playgrounds please? :)
