### ISSUE TITLE
Elaborate more on "functions in Swift are first-class values"

### ISSUE THREAD

**Issue by jjac** [objcio/functional-programming-in-swift#21]
Version 2014-10-01, page 10, first paragraph:

By your definition of functions as "first-class values" functions (closures) are also first class values in Apple-C and hence Objective-C and I agree they are.

Since I understand your book to be a praise for Swift in comparison to Objective-C, it would be helpful to elaborate on the _differences_ regarding the use/usability of functions/closures in those languages. If this is not appropriate in an introductory chapter like "thinking Functionally" I would at least expect some pointers/keywords in the above mentioned paragraph with a promise to clarify later in the book.

**Comment by chriseidhof** [comment]
We updated this in the latest version.
