### ISSUE TITLE
ePub version does not have syntax colors and Figure numbers

### ISSUE THREAD

**Issue by wigging** [objcio/functional-programming-in-swift#45]
I am using iBooks v1.1 on Yosemite to view the ePub version of your book.  I noticed that none of the syntax coloring and Figure numbers show up when compared to the PDF version (see below for a comparison).  As you can see in the comparison images, the PDF version is much easier to read and the formatting is more consistent.

ePub version:

![ebook](https://cloud.githubusercontent.com/assets/6828967/5255597/448563a6-798b-11e4-8d9f-01028f1d4c07.png)

PDF version:

![pdfpage](https://cloud.githubusercontent.com/assets/6828967/5255600/4b992e52-798b-11e4-98fe-21820512add7.png)

**Comment by chriseidhof** [comment]
Thanks! We're aware of this. We will put in some more effort into better versions for eReaders (also looking in to Kindle support), but currently the "preferred" version is the PDF. Hopefully we can add syntax highlighting to the epub sometime soon.
