### ISSUE TITLE
ePub transparent backgrounds on images

### ISSUE THREAD

**Issue by lvnyk** [objcio/functional-programming-in-swift#46]
When using a night display mode in iBooks (the one with black background and white text) some of the figures (Tries, marked fig 9.1 in pdf, Bar graph, marked fig 10.3 in pdf) are not visible, due to the transparent image background and black contents.

**Comment by chriseidhof** [comment]
We'll try to make the ePub image non-transparent in the next release. Thanks for the heads up.
