### ISSUE TITLE
ePub version appears to have a fixed maximum page width.

### ISSUE THREAD

**Issue by AlanQuatermain** [objcio/functional-programming-in-swift#47]
Long story short, this looks rather nasty, and is especially annoying when you try to open the book fullscreen on your secondary monitor:

![screen shot 2014-12-05 at 2 08 54 pm](https://cloud.githubusercontent.com/assets/11450/5323758/485a4ef6-7c88-11e4-8355-3da388da86d4.png)

**Comment by chriseidhof** [comment]
Absolutely. There's no real max-width in here, but if you can find a workaround, do let us know! Closing this for now.
