### ISSUE TITLE
Typo in The Value of Immutability ("pure programming languages")

### ISSUE THREAD

**Issue by MihaiDamian** [objcio/functional-programming-in-swift#56]
In the Discussion section of the 'The Value of Immutability' chapter "pure programming languages" should be replaced with "pure functional programming languages".

**Comment by chriseidhof** [comment]
I'm not sure if it's technically a typo, as it's not about the functional aspect, but really about the purity. @wouter-swierstra wdyt?

**Comment by wouter-swierstra** [comment]
Hmm. Both would work. The focus here is really on the purity, regardless of the programming paradigm. Let's keep it as it stands for now.
