### ISSUE TITLE
"Enumerations > The Algebra of Data Types" not very clear for me

### ISSUE THREAD

**Issue by hartbit** [objcio/functional-programming-in-swift#57]
Hi there,

I have some fairly good memories of studying Haskell and Functional Programming at University, so most of the concepts presented in the book feel natural. But I could really do with more examples and explanations for the section entitled *The Algebra of Data Types* in the *Enumerations* chapter. Here are the questions I'm left with after reading it:

> ... for any type `T`, the types `Add<T, Zero>` and `T` are isomorphic. It is fairly easy to prove this. We can use `InLeft` to define a function converting `T` to `Add<T, Zero>`, and the conversion in the other direction can be done by pattern matching.

This is not obvious to me. I can define the function `f` that converts from T to Add<T, Zero>:

```swift
func f<T>(t: T) -> Add<T, Zero> {
	return .InLeft(Box(t))
}
```

But I can't figure out how to define the function `g` that converts from Add<T, Zero> to T:

```swift
func g<T>(add: Add<T, Zero>) -> T {
	switch (add) {
	case let .InLeft(box):
		return box.unbox
	case let .InRight(box):
		return box.unbox // 'Zero' is not convertible to 'T'
	}
}
```

But that's not all. Later on, here are the next statements:

> `Times<One, T>` is isomorphic to `T`
> `Times<T, U>` is isomorphic to `Times<U, T>`

I'm ok with that, and the definitions are fairly obvious.

> `Times<Zero, T>` is isomorphic to `Zero`

Here, I don't see how to define the conversion function from `Zero` to `Times<Zero, T>`:

```
func f<T>(zero: Zero) -> Times<Zero, T> {
	return Times(fst: zero, snd: t) // No T values
}
```

Any help? :)

**Comment by wouter-swierstra** [comment]
Hi @hartbit 

The trick is that there is no value of type `Zero`. In particular, this lets you define the following function:

```swift
func zeroElim<T> (x : Zero) -> T {
    switch x {
    }
}
```

Because there is no value of type Zero, you can promise to produce a value of *any* if you were given one. Using `zeroElim` it should be pretty easy to fill in the missing branches (or just pattern match on the element of type `Zero` in this style).

You might also find Brand Williams's recent blogpost interesting (if you haven't seen it already): 

  http://www.fewbutripe.com/swift/math/2015/01/06/proof-in-functions.html

**Comment by hartbit** [comment]
Thanks a lot for the explanation and the link! I was reading the linked article and read:

> Some languages call this type Bottom (⊥).

University memories coming back :D Never thought I'd use this again. Who would have thought?

Concerning the book, do you think you'll add more details to that section?

**Comment by wouter-swierstra** [comment]
>
> Concerning the book, do you think you'll add more details to that section?
>

We don't have any concrete plans at the moment. If you have any suggestions
-- please let us know!

  Wouter
