### ISSUE TITLE
Weird sentences

### ISSUE THREAD

**Issue by westerlund** [objcio/functional-programming-in-swift#58]
I think I've found some typos and/or merging mistakes.

```
Please note:** There’s currently a bug in Xcode Playgrounds that prevents that causes an error when trying to initialize a CIImage in a playground.
```
should be (get rid of `that prevents`)
```
Please note:** There’s currently a bug in Xcode Playgrounds that causes an error when trying to initialize a CIImage in a playground.
```

And while reading
```
The solution is simple and elegant. It is quite different from what you might write, had you just refactored the inRange4 function into separate methods.
```
my head catches fire, I'm not sure if it is me or if the sentence is a bit off.

Anyway, thanks for a really interesting book!

Best,

**Comment by wouter-swierstra** [comment]
Thanks @westerlund! I've fixed the first issue in our repository.

As for the second issue. Is this more clear?

'''
It is quite different from what you might write, if had you naively refactored the `inRange4` function into separate methods.
'''

Thanks again for the feedback!

**Comment by deutschbitte** [comment]
@wouter-swierstra If you go with your rephrased option, it should be:

It is quite different from what you might write if had you naively refactored the ´inRange4´ function into separate methods.

**Comment by westerlund** [comment]
perfect!
now for the second sentence I think @deutschbitte nails it!

**Comment by wouter-swierstra** [comment]
Thanks @deutschbitte. I've fixed this.
