### ISSUE TITLE
Chapter 5: The provided autoclosure to the nil coalescing operator

### ISSUE THREAD

**Issue by carlosypunto** [objcio/functional-programming-in-swift#60]
In Xcode 6.1 when you provide an autoclosure to the nil coalescing operator in Chapter 5, the autoclosure must be called with () otherwise it fails.

See gist: https://gist.github.com/carlosypunto/0e4f40cea70acd34a1c0

**Comment by chriseidhof** [comment]
Where exactly do you mean? I think we're calling it with `()`, no?

**Comment by carlosypunto** [comment]
http://i.imgur.com/KIhqhz0.png

**Comment by chriseidhof** [comment]
Ah! So that example is actually a "first attempt" at writing ??. It's not the real implementation. That follows later. In that definition, we solve it without `auto_closure`. Does that make sense?

**Comment by carlosypunto** [comment]
It continues with this:

For example, we would need to write:

    myOptional ?? { myDefaultValue }

It should not be:

   myOptional ?? { myDefaultValue }()

**Comment by carlosypunto** [comment]
Sorry, you're right

**Comment by chriseidhof** [comment]
Yes, but it's still very good feedback, we will see if we can clarify this section. Thanks a lot!
