### ISSUE TITLE
Problem with barGraph in Chapter 10: Diagrams

### ISSUE THREAD

**Issue by kellygerber** [objcio/functional-programming-in-swift#61]
The code for diagrams in Chapter 10 works great in a Mac app. However, I got an error when trying the barGraph() example. I was able to resolve the issue by changing the generic variable in the Dictionary extension from (Key, Value) to Element:

<pre>
extension Dictionary {
     var keysAndValues: [Element]  {
         var result: [Element] = []
         for item in self {
             result.append(item)
        }
       return result
    }
}
</pre>
I don't know why that made a difference for me, but now the bar graph is working great as well. Anyway, I am really enjoying the book.

**Comment by chriseidhof** [comment]
Hm, interesting. Here it seems to work perfectly on both iOS and OS X, except in playgrounds...
