### ISSUE TITLE
Elaborate more about "Trie"

### ISSUE THREAD

**Issue by carlosypunto** [objcio/functional-programming-in-swift#62]
In the second part of chapter 9 "Autocompletion Using Tries", it is very clear as a Trie is structured and ways to cross it. But do not you explain how to populate it. I tried to do it line by line and I can not find the way. Besides, being Trie one struct, I do not know if is posible,  by a function to facilitate the work, to add subscripts to a Trie already created.
I miss in the book some kind of use sample

**Comment by wouter-swierstra** [comment]
Thanks @carlosypunto – I've been updating this chapter and extending it a bit. Unfortunately, the tries data structure still manages to trigger some bugs in Swift, giving weird error messages. I'd love to provide a larger example, but haven't worked out how to do so yet. For the moment, I have extended the chapter to include the definition of insertion and some discussion about what goes wrong. The updated chapter should be available upon our next release.

**Comment by carlosypunto** [comment]
Would know tell me when the next update will be ready? I am anxious to read the new version of the book. Thank you very much for your attention.

**Comment by wouter-swierstra** [comment]
Sure thing. @chriseidhof and @floriankugler are preparing a big release on an unrelated project. We're hoping to do some more work over the coming weeks.

**Comment by carlosypunto** [comment]
If you do not find a way to programmatically create a Trie. Could include, at least in the Playground a Trie already created, to play with, such as the following:

    let words = Trie(isElem: false, children: [
        Character("b"): Trie(isElem: false, children: [
            Character("e"): Trie(isElem: false, children: [
                Character("e"): Trie(isElem: true, children: [:])
                ])
            ]),
        Character("c"): Trie(isElem: false, children: [
            Character("a"): Trie(isElem: false, children: [
                Character("r"): Trie(isElem: true, children: [
                    Character("e"): Trie(isElem: true, children: [:]),
                    Character("t"): Trie(isElem: true, children: [
                        Character("a"): Trie(isElem: false, children: [
                            Character("g"): Trie(isElem: false, children: [
                                Character("e"): Trie(isElem: true, children: [:])
                                ])
                            ])
                        ])
                    ]),
                Character("s"): Trie(isElem: false, children: [
                    Character("h"): Trie(isElem: true, children: [:])
                    ]),
                Character("m"): Trie(isElem: true, children: [
                    Character("p"): Trie(isElem: true, children: [
                        Character("i"): Trie(isElem: false, children: [
                            Character("n"): Trie(isElem: false, children: [
                                Character("g"): Trie(isElem: true, children: [:])
                                ])
                            ])
                        ])
                    ])
                ])
            ]),
        Character("d"): Trie(isElem: false, children: [
            Character("o"): Trie(isElem: false, children: [
                Character("g"): Trie(isElem: true, children: [:])
                ])
            ])
        ])

**Comment by wouter-swierstra** [comment]
Hi @carlosypunto -- good news. The latest versions of Swift do address the issues we had. We're updating the chapter at the moment, and will release a working playground alongside it once we're done.

**Comment by carlosypunto** [comment]
Maybe, you can include a helper function like this:

    extension String {
        subscript (i: Int) -> Character {
            return self[advance(self.startIndex, i)]
        }
        var characters: [Character] {
            var chars = [Character]()
            for i in 0..<count(self) {
                let char = self[i]
                chars.append(char)
            }
            return chars
        }
    }
    
    lookup("ca".characters, words)
    lookup("car".characters, words)
