### ISSUE TITLE
Chapter 8 - Compile error

### ISSUE THREAD

**Issue by danielgomezrico** [objcio/functional-programming-in-swift#63]
Hi

Using `XCode 6.2 beta`.

I'm looking at chapter 8 (enums) and it shows an example with `NSStringEncoding`.
If I didn't misunderstood it says that the next line must work but it doesn't compile neither.

`enum Test: Int {
	case First = 0
	case Second = 1
	case Third = 2
}

let first = Test.First + Test.Second`

is there an error?

**Comment by chriseidhof** [comment]
Well, this is only valid in Objective-C. There, adding two enums should work, whereas in Swift it shouldn't. Does that clarify things?

**Comment by danielgomezrico** [comment]
Sure, thanks
