### ISSUE TITLE
Ch 12: `one` function unexplained

### ISSUE THREAD

**Issue by jasongregori** [objcio/functional-programming-in-swift#64]
In chapter 12, a `one` function that creates SequenceOf's is used without any explanation. Because I had just seen the explanation of the `one` function that creates GeneratorOf's in the last chapter and am just learning this stuff for the first time, I thought this was the same function. Confused, I went back the last chapter and realized that GeneratorOf's are also SequenceType's. That confused me even more and I spent a day trying to figure out what was going on. 

I finally realized this was a different `one` function and found the code in the back of the book. Anyways, I think you should just mention right before that this is a "one function for SequenceOf's, similar to the one function for GeneratorOf's in the last chapter. 

Thanks!

**Comment by wouter-swierstra** [comment]
Thanks for reporting this @jasongregori! I've added a sentence clarifying this. It should show up in the next release of the book.
