### ISSUE TITLE
Duplicate diagrams in chapter 1

### ISSUE THREAD

**Issue by moreindirection** [objcio/functional-programming-in-swift#65]
In the print edition, the two battleship diagrams on pages 8 and 9 are identical, but they have different captions and are supposed to represent different things. One is supposed to depict enemy ships - the other is supposed to depict friendly ships. Both of the diagrams show friendly ships only.

**Comment by wouter-swierstra** [comment]
@moreindirection Thanks for reporting this! It's fixed in the current print version of the book.
