### ISSUE TITLE
Code error in Battleship example

### ISSUE THREAD

**Issue by moreindirection** [objcio/functional-programming-in-swift#66]
On page 13 of the print edition, there's an error in the `inRange` code. The definition `targetRegion` uses `ownPosition` instead of `target`.

**Comment by wouter-swierstra** [comment]
Thanks for reporting this -- but I don't think it's wrong...

The `rangeRegion` is the annulus around the origin;
the `targetRegion` shifts this to take the current position of the ship into account
(the choice of name here is confusing; it should perhaps be called `currentRangeRegion`)

The only place we should use the `target` position is at the very end: when we apply the `Region` to the `target` to check that if it is in range or not.
