### ISSUE TITLE
Chapter 3: add3 explicit name falsity

### ISSUE THREAD

**Issue by Jessy-** [objcio/functional-programming-in-swift#67]
"To call add3 we must, however, provide an explicit name for the second argument"

No, just use an underscore:  func add3(x: Int)(_ y: Int) → Int

**Comment by wouter-swierstra** [comment]
Thanks for filing this @Jessy- ! We still need to update the book to Swift 1.2.

**Comment by chriseidhof** [comment]
I just updated this in our private repo, we'll include this in the next release. Thanks once again!
