### ISSUE TITLE
Chapter 2: rangeRegion function isn't inclusive of circle edge, as was its predecessor.

### ISSUE THREAD

**Issue by Jessy-** [objcio/functional-programming-in-swift#68]
let rangeRegion = difference(circle(range),  circle(minimumDistance))

is exclusive for circle(minimumDistance). The previous version was inclusive:

return targetDistance <= range && targetDistance >= minimumDistance

**Comment by wouter-swierstra** [comment]
Well spotted -- we'll fix this in the next edition.
