### ISSUE TITLE
Cap. 5  NSNotFound != -1

### ISSUE THREAD

**Issue by ignazioc** [objcio/functional-programming-in-swift#69]
At page 58 of the PDF  you say `"NSNotFound is defined as -1"` but as far as I know `NSNotFound` is `NSIntegerMax` that is `LONG_MAX 2147483647L`

But nevertheless the example is right, because
`
if ([nil rangeOfString:@"swift"].location != NSNotFound]) {
`
will execute the `else`branch because the result is 0 and 0 != NSNotFound

**Comment by chriseidhof** [comment]
Thanks, great catch. I just updated the internal repo, will be included in the next update.  Thanks @ignazioc
