### ISSUE TITLE
Chapter 3: colorGenerator Issue

### ISSUE THREAD

**Issue by Nativeman** [objcio/functional-programming-in-swift#70]
So when I attempt to run the colorOverlay, which uses the colorGenerator function; colorGenerator returns the error seen in the photo below:

![screen shot 2015-03-12 at 5 29 31 pm](https://cloud.githubusercontent.com/assets/8988852/6629576/717d4e54-c8dd-11e4-8616-8116632dcf1b.png)

But I still get an image output at the bottom of playgrounds: 
![screen shot 2015-03-12 at 5 31 35 pm](https://cloud.githubusercontent.com/assets/8988852/6629601/a983d89a-c8dd-11e4-9918-6cad0d4b503d.png)

.Not exactly sure what I am doing, though I am running Swift 1.2.  Any thoughts?

**Comment by wouter-swierstra** [comment]
Thanks for reporting this @Nativeman. @floriankugler or @chriseidhof do you know what might be going on here?

**Comment by floriankugler** [comment]
Interesting, we'll have to take a closer look at this. We'll completely revisit all the content for Swift 1.2 and the new playground features soon.

**Comment by floriankugler** [comment]
It seems to be an odd behavior of playgrounds. I get the same error, but at the end it works anyway. Nothing we can do about it I suspect...

**Comment by inatu** [comment]
Still got this error, anyone can tell me what is wrong, and how to fix this error message

**Comment by floriankugler** [comment]
@inatu currently the only thing we can do is to wait for future Xcode versions to fix this bug, it seems...
