### ISSUE TITLE
Chapter 3: composeFilters example

### ISSUE THREAD

**Issue by ctews** [objcio/functional-programming-in-swift#72]
let myFilter1 = composeFilters(blur(blurRadius), colorOverlay(overlayColor))

shouldn't it be:

let myFilter1 = composeFilters(blur(blurRadius), colorOverlay(overlayColor)) (image)

Sorry for bad formatting, only iPhone accessible. Also not tested in XCode so please correct me if I'm wrong. But since composeFilters returns type Filter it should be right.

**Comment by chriseidhof** [comment]
Hey @ctews ! The first line creates a new filter, whereas the second line creates a new image... does that make sense?

**Comment by ctews** [comment]
Ah sorry, brain was absence then! Thanks for clarifying!

My suggestion would be for a next version of the book to put the subchapter about currying as an introduction to Chapter 3, because for me it would be just more intuitive to understand the mechanics and get into the right mental model :)

**Comment by chriseidhof** [comment]
Great suggestion, thanks!

On Sat, Mar 14, 2015 at 6:38 PM, Christoffer Tews <notifications@github.com>
wrote:

> Ah sorry, brain was absence then! Thanks for clarifying!
>
> My suggestion would be for a next version of the book to put the
> subchapter about currying as an introduction to Chapter 3, because for me
> it would be just more intuitive to understand the mechanics and get into
> the right mental model :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/objcio/functional-programming-in-swift/issues/72#issuecomment-80626169>
> .
>



-- 
Chris Eidhof
