### ISSUE TITLE
numberOfIterations variable never defined

### ISSUE THREAD

**Issue by SixFiveSoftware** [objcio/functional-programming-in-swift#73]
Excellent book, thank you! In the QuickCheck chapter, func check1 (and several others thereafter) use a for-in loop with 'numberOfIterations' being the end of the half-closed range, but 'numberOfIterations' is never defined. Is this supposed to be? If it's just a placeholder to show the concept of what's going on, then why make such a detailed println statement utilizing the numberOfIterations variable? The surrounding text context is unclear as to what that should be.

**Comment by chriseidhof** [comment]
Thanks! In the digital book, we include this in the playground... but still a fair point. We'll consider clarifying this in the next release.
