### ISSUE TITLE
Function composition order

### ISSUE THREAD

**Issue by carlosypunto** [objcio/functional-programming-in-swift#74]
This is not about one issue of the book, it's a little doubt about function composition. In the chapter 3 of the book you use filter composition from right to left. I think most obvious/readable composing functions from left to right (Case B on this [gist](https://gist.github.com/carlosypunto/4ddc0187fdc9a3e8e5e7)). Do you think that is a bad practice? Does this breaks some pattern or convention?

**Comment by chriseidhof** [comment]
I think it's a different way of doing things. The first case is more like mathematical function composition, which is where functional programming comes from. So it's more of a common practice in FP to do it this way around.
