### ISSUE TITLE
Error with CIConstantColorGenerator in chapter 3

### ISSUE THREAD

**Issue by siancu** [objcio/functional-programming-in-swift#77]
With Xcode 6.3.1 in 10.10.3, I get an error in the 03-Wrapping-Core-Image.playground. It seems that the CIConstantColorGenerator CIFilter isn't found.

Any ideas what might be wrong?

![screenshot 2015-04-24 16 34 56](https://cloud.githubusercontent.com/assets/39668/7320972/e706afb0-ea9f-11e4-8e63-ae33970f5f1d.png)

**Comment by adamb** [comment]
I get a different error.  Also on Xcode 6.3.1 but 10.10.2

I also tried converting this code to run as an iOS app but it fails on the return filter.outputImage saying that it found an unexpected nil while unwrapping an optional.  I don't see any optionals there...

![image](https://cloud.githubusercontent.com/assets/4441/7323481/bffe0bfc-ea63-11e4-9dee-daad5a7ff7c0.png)

**Comment by adamb** [comment]
I get *output nil* when trying the following code.  It crashes on the next line, the return, complaining about the unwrapping an optional...  Any ideas?

```swift
func colorGen(color: UIColor) -> Filter {
    return { _ in
        let parameters = [kCIInputColorKey: color] // also tried ["inputColor": color]
        let filter = CIFilter(name: "CIConstantColorGenerator", withInputParameters: parameters)
        if (filter.outputImage == nil) {println("output nil")}
        return filter.outputImage
    }
}
let url = NSURL(string: "http://www.objc.io/images/covers/16.jpg")
let image = CIImage(contentsOfURL: url)
let overlayColor = UIColor.redColor().colorWithAlphaComponent(0.2)
let redImage = colorGen(overlayColor)(image)
```

**Comment by floriankugler** [comment]
@siancu I see the same error as you do, but the playground still works for me, i.e. all the output images look are there. This seems to be some playground glitch.

@adamb In your first comment there's a return statement missing before `filter.outputImage`. In your iOS project, you'll probably run into two issues:

1. `CIImage`'s initializer that takes an URL returns `nil` for me. This might be a playground issue as well, but I haven't checked that. It works if you use the initializer that takes a `NSData` object instead.
2. You'll need to convert the `UIColor` to a `CIColor`

**Comment by adamb** [comment]
Thanks @floriankugler!  `UIColor` was not working for me at all.  `CIColor` did the trick!

**Comment by fmcauley** [comment]
```CIColor``` also worked for me. ```UIColor``` was returning a nil value.

**Comment by fmcauley** [comment]
Purchased the book awhile ago. Finally getting around to working through the examples. The concept of functions that return functions is still hard to warp my head around!

**Comment by Slankerful** [comment]
I've had similar problems which were solved by the following:

func generate(colour: UIColor) -> Filter {
    return {
        image in
        let parameters = [
            kCIInputColorKey: CIColor(cgColor: colour.cgColor)
        ]
        guard let filter = CIFilter(name: "CIConstantColorGenerator", withInputParameters: parameters)
            else { fatalError() }
        guard let outputImage = filter.outputImage else { fatalError() }
        return outputImage.cropped(to: image.extent)
    }
}
It appears the returned output image needs to be cropped otherwise you get an exception if you're in a Playground.
