### ISSUE TITLE
fold_left vs reduce vs fold_right

### ISSUE THREAD

**Issue by ge0rge** [objcio/functional-programming-in-swift#79]
On page 40, after implementing custom reduce function, we have:
> In some functional languages, such as OCaml and Haskell, reduce functions are called `fold` or `fold_right`

That custom reduce function traverses array from left to right and is therefore more of a `fold_left`, isn't it?

**Comment by wouter-swierstra** [comment]
Thanks for reporting this @ge0rge -- you're right of course. I've fixed this in our private repository; we'll include this in our next release.
