### ISSUE TITLE
int vs floating point in Why Optionals?

### ISSUE THREAD

**Issue by ole** [objcio/functional-programming-in-swift#82]
> We can pass in `nil` for the name of a country, and we get back a result of `0.0`.

This should be "…get back a result of `0`." since you’re using ints everywhere for the population values.

![img_0330](https://cloud.githubusercontent.com/assets/5010/7410819/a892128c-ef32-11e4-8f1e-cb927198a8a1.PNG)

**Comment by chriseidhof** [comment]
Great catch!
