### ISSUE TITLE
Class vs. instance methods

### ISSUE THREAD

**Issue by ole** [objcio/functional-programming-in-swift#85]
> In Objective-C and many other object-oriented languages, it is common for class methods to be coupled through shared instance variables.

This is at least confusing, if not wrong. Class methods (in the sense of methods on the class type) have no access to instance variables, and class variables don't exist in Obj-C. I get that you mean instance methods here ("methods that are part of a class") but I think you should rephrase this.

![img_0334](https://cloud.githubusercontent.com/assets/5010/7429026/81915f08-effa-11e4-8adb-7cc7be10a284.PNG)

**Comment by chriseidhof** [comment]
@ole what do you think about this (removing class altogether):

> In Objective-C and many other object-oriented languages, it is common for methods to be coupled through shared instance variables.

**Comment by ole** [comment]
Yes, much better.
