### ISSUE TITLE
Replace (count > 0) with !isEmpty?

### ISSUE THREAD

**Issue by ole** [objcio/functional-programming-in-swift#86]
Minor nitpick: would it be better to replace the `(count > 0)` condition with `!isEmpty` here?

![img_0335](https://cloud.githubusercontent.com/assets/5010/7429036/c29cd018-effa-11e4-8ab6-868daf061d98.PNG)

**Comment by chriseidhof** [comment]
Yes, I replaced it with isEmpty (and swapped the : operands around)
