### ISSUE TITLE
Appendix: refactor String.characters

### ISSUE THREAD

**Issue by ole** [objcio/functional-programming-in-swift#91]
The `String.characters` property can be written shorter:

```
extension String {
    var characters: [Character] {
        return Array(self)
    }
}
```

![screen shot 2015-05-03 at 20 27 11](https://cloud.githubusercontent.com/assets/5010/7446256/f8ee0b44-f1d2-11e4-83e3-43f8dfbce6a4.png)

**Comment by chriseidhof** [comment]
Thanks!
