### ISSUE TITLE
Spreadsheet/GUI: error in code sample

### ISSUE THREAD

**Issue by ole** [objcio/functional-programming-in-swift#92]
The line:

    formulas = initialValues.map { _ in "0" }

should be:

    formulas = initialValues.map { { "\($0)" } }

It's correct in the sample code but not in the PDF (2015-04-22).

![screen shot 2015-05-05 at 17 52 27](https://cloud.githubusercontent.com/assets/5010/7476717/b88bfd8a-f34f-11e4-8c97-8e038243148c.png)

**Comment by chriseidhof** [comment]
Ah, good catch. So in the sample project it initializes with the values 1 to 10. Here, the formulas get initialized with 0 but the results with 1 to 10. I changed it so that it's all zeroes.
