### ISSUE TITLE
Spreadsheet/GUI: using KVO?

### ISSUE THREAD

**Issue by ole** [objcio/functional-programming-in-swift#93]
> Because of key-value observing, the GUI will update automatically:

This sentence seems wrong. The code calls `reloadData()` explicitly after `calculateExpressions()` and I don’t see any KVO.

![screen shot 2015-05-05 at 17 57 45](https://cloud.githubusercontent.com/assets/5010/7476835/74d56ae4-f350-11e4-8871-9e584b052d5b.png)

**Comment by chriseidhof** [comment]
Thanks! Just removed that sentence.
