### ISSUE TITLE
Typo in flatMap implementation

### ISSUE THREAD

**Issue by danielpi** [objcio/functional-programming-in-swift#94]
Hi,

On page 52 of the pdf the flatMap function is defined as this

    func flatMap<A, B>(x: A?, f: A -> B?) -> B? {

Which should be

    func flatMap<A, B>(optional: A?, f: A -> B?) -> B? {

I think. Thanks for writing the book by the way. I'm really enjoying it.

Daniel.

**Comment by floriankugler** [comment]
@danielpi Thanks for the hint! We've fixed this internally and include it in the next update.
