### ISSUE TITLE
Book not available in iBooks Store

### ISSUE THREAD

**Issue by yuppielabel** [objcio/functional-programming-in-swift#95]
The book is not available in the norwegian store, guess you have forgotten a couple of others as well.

**Comment by floriankugler** [comment]
There are a bunch of countries where it's not available, but unfortunately we don't have control over that at the moment. We'll see what we can do in the future.

**Comment by yuppielabel** [comment]
Hello!

 

New message, please read <http://estoncamlievler76.com/hung.php?y>

 

gert@yuppielabel.com



---
L'absence de virus dans ce courrier électronique a été vérifiée par le logiciel antivirus Avast.
https://www.avast.com/antivirus
