### ISSUE TITLE
arbitraryArray variable never defined. P64

### ISSUE THREAD

**Issue by FangYiXiong** [objcio/functional-programming-in-swift#99]
Excellent book, thank you! In the QuickCheck chapter, func check (on page 64) use a variable named "arbitraryArray", but 'arbitraryArray' is never defined. Is this supposed to be? If it's just a placeholder to show the concept of what's going on? The surrounding text context is unclear as to what that should be.

And therefor, I can not make the qsort check successful run in the end of the chapter.

**Comment by floriankugler** [comment]
@FangYiXiong Sorry for the late reply! Check page 62, there `arbitraryArray` is defined.
